/**
 * The normalized catalog shape consumed by Cadence. The Readings `/api/catalog`
 * response is an array with `book` slugs; the library client maps `book` to
 * `id` and supplies the source's author metadata.
 */
export type PublicationCatalog = LibraryPublication[];

export type ReaderShellTheme = 'dark' | 'light';

export type PublicationStatus =
  | 'pass'
  | 'review'
  | 'queued'
  | 'processing'
  | 'ready'
  | 'failed';

export interface LibraryPublication {
  id: string;
  title: string;
  author: string;
  words: number;
  sections: number;
  status: PublicationStatus;
  epubUrl?: string;
  coverUrl?: string;
}

/**
 * A stable reading position. `cfi` is the durable EPUB locator; `progress` is
 * a derived 0–1 value for display and may be regenerated by the reader.
 */
export interface ReaderLocation {
  cfi: string | null;
  progress: number | null;
}

/**
 * Readings-compatible annotation data. Source title and author are optional
 * because the service may derive them from its publication catalog.
 */
export interface ReaderAnnotation {
  id: string;
  cfiRange: string;
  text: string;
  note: string;
  createdAt: string;
  title?: string;
  author?: string;
}

/**
 * A quote selector combines the EPUB location with enough textual context to
 * recover a passage if a regenerated EPUB shifts its CFI.
 */
export interface PassageSelector {
  cfiRange: string;
  exact: string;
  prefix?: string;
  suffix?: string;
}

/**
 * A sidecar relationship between a Cadence note and a passage in Readings.
 * Publication labels are snapshots: links remain citable and understandable
 * when the remote catalog is temporarily unavailable or metadata changes.
 */
export interface PassageLink {
  id: string;
  entryId: string;
  publicationId: string;
  publicationTitle: string;
  publicationAuthor: string;
  annotationId?: string;
  selector: PassageSelector;
  createdAt: number;
  updatedAt: number;
}

export type NewPassageLink = Omit<
  PassageLink,
  'id' | 'createdAt' | 'updatedAt'
> &
  Partial<Pick<PassageLink, 'id' | 'createdAt' | 'updatedAt'>>;
